In [2]:
import numpy as np
import array
import sys

1. Какие еще существуют коды типов?

• b: np.int8 — 8-битное целое число без знака

• B: np.uint8 — np.bool_ — Логический тип данных (True или False)

• l: np.int32 — 32-битное целое число со знаком (по умолчанию)

• L: np.uint32 — 32-битное беззнаковое целое число

• q: np.int64 — 64-битное целое число со знаком

• Q: np.uint64 — 64-битное беззнаковое целое число

• h: np.int16 — 16-битное целое число со знаком

• H: np.uint16 — 16-битное беззнаковое целое число

• f: np.float32 — 32-битное число с плавающей точкой

• d: np.float64 — 64-битное число с плавающей точкой (по умолчанию)

• u: Юникод строка фиксированной длины (например, U10 для строки длиной 10 символов)


In [ ]:
## 2. Напишите код, подобный приведенному выше, но с другим типом

a = array.array('u', ['a', 'b', 'c'])
print(a, sys.getsizeof(a), type(a))

array('u', 'abc') 92 <class 'array.array'>


In [ ]:
## 3. Напишите код для создания массива с 5 значениями, располагающимися через равные интервалы в диапазоне от 0 до 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
## 4. Напишите код для создания массива с 5 равномерно распределенными случайными значениями в диапазоне от 0 до 1

np.random.rand(5)

array([0.1731258 , 0.97004919, 0.95583874, 0.27421177, 0.22476715])

In [ ]:
## 5. Напишите код для создания массива с 5 нормально распределенными случайными значениями с мат. ожиданием = 0 и дисперсией 1

np.random.normal(0, 1, 5)

array([ 0.47382016, -0.28683633,  1.97124921, -0.17044319, -0.48680203])

In [ ]:
## 6. Напишите код для создания массива с 5 случайными целыми числами в диапазоне [0, 10)

np.random.randint(0, 10, 5)

array([3, 0, 9, 1, 5])

In [ ]:
## 7. Написать код для создания срезов массива 3 на 4
## - первые две строки и три столбца
## - первые три строки и второй столбец
## - все строки и столбцы в обратном порядке
## - второй столбец
## - третья строка

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a[:2, :3])
print('                       ')

print(a[:, 1:2])
print('                       ')

print(a[::-1, ::-1])
print('                       ')

print(a[:, 1])
print('                       ')

print(a[-1:])
print('                       ')

[[1 2 3]
 [5 6 7]]
                       
[[ 2]
 [ 6]
 [10]]
                       
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
                       
[ 2  6 10]
                       
[[ 9 10 11 12]]
                       


In [6]:
# 8. Продемонстрируйте, как сделать срез-копию
a = np.arange(10)
print(a[1:5])

a_copy=a[1:5].copy()
print(a_copy)

a_copy[0]=100
print(a, a_copy)

[1 2 3 4]
[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [100   2   3   4]


In [14]:
# 9. Продемонстрируйте использование newaxis для получения вектора-столбца и вектора-строки

b = np.array([1, 2, 4])

print('Вектор_столбец:')
print(b[:, np.newaxis])

print('Вектор_строка:')
print(b[np.newaxis, :])

Вектор_столбец:
[[1]
 [2]
 [4]]
Вектор_строка:
[[1 2 4]]


In [23]:
# 10. Разберитесь, как работает метод dstack
#Складывает массивы последовательно по глубине (вдоль третьей оси)

x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])

r1 = np.dstack([x,y,z])
print(r1)
print('____________________')

a = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
b = np.array([[22,23], [24,25]])
r2 = np.dstack([a,b])

print(r2)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]
____________________
[[[ 1  2 22]
  [ 3  4 23]]

 [[ 5  6 24]
  [ 7  8 25]]]


In [42]:
# 11. Разберитесь, как работают методы split, vsplit, hsplit, dsplit
#split разделяет массив на части равной длины
#vsplit разделяет массив «по вертикали» (по строкам)
#hsplit разделяет массив «по горизонтали» (по столбцам)
#dsplit разделяет массив «по глубине» (по третьей оси)

a = np.arange(9).reshape(3, 3)
print(a)
print('split, 0 axis')

print(np.split(a, 3, 0))
print('split, 1 axis')

print(np.split(a, 3, 1))
print('vsplit')

print(np.vsplit(a, 3))
print('hsplit')

print(np.hsplit(a, 3))
print('3axis array')

b = np.arange(12).reshape(3,2,2)
print(b)
print('dsplit')
print(np.dsplit(b, 2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
split, 0 axis
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
split, 1 axis
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
vsplit
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
hsplit
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
3axis array
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
dsplit
[array([[[ 0],
        [ 2]],

       [[ 4],
        [ 6]],

       [[ 8],
        [10]]]), array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]]])]


In [54]:
# 12. Привести пример использования всех универсальных функций, которые я привел
# - - / // ** %

a = np.arange(5)

print(-a)
print(np.negative(a))

print(a-1)
print(np.subtract(a, 1))

print(a/2)
print(np.divide(a, 2))

print(a//2)
print(np.floor_divide(a, 2))

print(a**2)
print(np.power(a, 2))

print(a%2)
print(np.remainder(a, 2))

[ 0 -1 -2 -3 -4]
[ 0 -1 -2 -3 -4]
[-1  0  1  2  3]
[-1  0  1  2  3]
[0.  0.5 1.  1.5 2. ]
[0.  0.5 1.  1.5 2. ]
[0 0 1 1 2]
[0 0 1 1 2]
[ 0  1  4  9 16]
[ 0  1  4  9 16]
[0 1 0 1 0]
[0 1 0 1 0]
