**Библиотека** **NumPy**

In [ ]:
import numpy as np
import array

In [ ]:
#Типы данных python

In [ ]:
import sys
x = 1
print(type(x))
print(sys.getsizeof(x))

x = 'hello'
print(type(x))

x = True
print(type(x))

<class 'int'>
28
<class 'str'>
<class 'bool'>


In [ ]:
l1 = list([])
print(sys.getsizeof(l1))

56


In [ ]:
l2 = list([1, 2, 3])
print(sys.getsizeof(l2))

88


In [ ]:
l3 = list([1, '2', True]) #вызывает замедления из-за динамической типизации => не подходит
print(sys.getsizeof(l3))

88


In [ ]:
a1 = array.array('i', [1, 2, 3]) #only one type
print(sys.getsizeof(a1))
print(a1)

92
array('i', [1, 2, 3])


In [ ]:
a = np.array([1, 2, 3,4,5])
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [ ]:
a = np.array([1.23, 2, 3,4,5]) #"Повышающее" приведение типов
print(type(a), a)

<class 'numpy.ndarray'> [1.23 2.   3.   4.   5.  ]


In [ ]:
a = np.array([1.7, 2, 3,4,5], dtype=int)
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [ ]:
a = np.array([range(i, i+3) for i in [2,4,6]]) #Последний элемент не генерируется
print(a, type(a))

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [ ]:
a = np.zeros(10, dtype=int)
print(a, type(a))
 #Сначала строки, потом стоблцы. Говорят размерность номер...
print(np.ones((3, 5), dtype=float))

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
print(np.full((4, 5), 3.1415))

[[3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]]


In [ ]:
print(np.arange(0, 20,2)) #first, last(without), step

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Массивы**

In [ ]:
np.random.seed(1) #с начальным значением 1, случайные числа всегда в одном и том же порядке

x1 = np.random.randint(10, size =3)
print(x1)

x2 = np.random.randint(10, size =(3,2))
print(x2)

x3 = np.random.randint(10, size =(3,2,2))
print(x3)

[5 8 9]
[[5 0]
 [0 1]
 [7 6]]
[[[9 2]
  [4 5]]

 [[2 4]
  [2 4]]

 [[7 7]
  [9 1]]]


In [ ]:
#Свойства массивов

#ndim число размерностей
#shape размер каждой размерности
#size общий размер массива(число элементов)

print(x1.ndim, x1.shape, x1.size)
print(x2.ndim, x2.shape, x2.size)
print(x3.ndim, x3.shape, x3.size)

1 (3,) 3
2 (3, 2) 6
3 (3, 2, 2) 12


In [ ]:
#ДОступ к элементам массива. Индексы (с 0)

a = np.array([1, 2, 3, 4, 5])

print(a[0])
print(a[-2])
a[1] = 20
print(a)

b = np.array([[1,2], [3,4]])
print(b[0,0])
print(b[-1,-1])
b[1, 0] = 100
print(b)

1
4
[ 1 20  3  4  5]
1
4
[[  1   2]
 [100   4]]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1., 2, 3, 4])

print(a)
print(b)

a[0] = 10.9 #Приводится к int, тип в массиве больше не меняется
print(a)

[1 2 3 4]
[1. 2. 3. 4.]
[10  2  3  4]


In [ ]:
# Срез [start:finish:step] [0:shape:1], finish не учитывается

a = np.array([1,2,3,4,5,6])
print(a[0:3:1])
print(a[:3])
print(a[3:])
print(a[1:5])
print(a[1:-1])
print(a[1::2])

print(a[::-1])

[1 2 3]
[1 2 3]
[4 5 6]
[2 3 4 5]
[2 3 4 5]
[2 4 6]
[6 5 4 3 2 1]


In [ ]:
#Срезы не копии, а части массива!
a = np.array([1,2,3,4,5,6])

b = a[:3]

b[0] = 100

print(a)

[100   2   3   4   5   6]


In [ ]:
a = np.arange(1,13)
print(a)
print(a.reshape(2,6)) #Размеры соответсвуют

# x = np.array([1,2,3])
# y = np.array([4,5])
# z = np.array([6])

# print(np.concatenate([x,y,z])) #Объединение

x = np.array([1,2,3])
y = np.array([4,5,6])

r1 = np.vstack([x,y]) #vertical
print(r1)

print(np.hstack([r1,r1])) #horizontal

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


Вычисления с массивами

In [ ]:
#Векторизированная операция - независимо  к каждому элементу массива

x = np.arange(10)
print(x)

print(x*2+1)

#Универсальные функции

print(np.add(np.multiply(x,2), 1))

# - - / // ** %
#np. abs, sin/cos/tan, exp, log

x = np.arange(5)

y = np.zeros(10)
print(np.multiply(x, 10, out=y[::2]))
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0. 10. 20. 30. 40.]
[ 0.  0. 10.  0. 20.  0. 30.  0. 40.  0.]


In [ ]:
x = np.arange(1,5)
print(x)

print(np.add.reduce(x)) #СВернули массив к одному значению через сумму

print(np.add.accumulate(x))

[1 2 3 4]
10
[ 1  3  6 10]


In [ ]:
#векторные произведения
x = np.arange(1,10)
print(np.add.outer(x,x))
print(np.multiply.outer(x,x))

[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
