Библиотека Pandas

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Pandas - расширение Numpy (структурированные массивы). Строки и столбцы индексируются метками, а не только числами
# Series, DataFrame, Index

In [8]:
## Series

data = pd.Series([0.25,0.5,0.75,1.0])
print(data)
print(type(data))
print(type(data.values))
print(type(data.index))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.range.RangeIndex'>


In [11]:
data = pd.Series([0.25,0.5,0.75,1.0])
print(data[0])
print(data[1:3])

0.25
1    0.50
2    0.75
dtype: float64


In [19]:
data = pd.Series([0.25,0.5,0.75,1.0], index=['a', 'b', 'c', 'd'])
print(data)

print(data['a'], data[0])

print(data['b':'d'])

print(type(data.index))

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25 0.25
b    0.50
c    0.75
d    1.00
dtype: float64
<class 'pandas.core.indexes.base.Index'>


<ipython-input-19-debb5b54c031>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(data['a'], data[0])


In [22]:
data = pd.Series([0.25,0.5,0.75,1.0], index=[1, 10, 7, 'd'])
print(data)

print(data[1])
print(data[10:'d'])

1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
0.25
10    0.50
7     0.75
d     1.00
dtype: float64


In [4]:
population_dict= {'city_1': 1001, 'city_2': 1002, 'city_3': 1003, 'city_4': 1004, 'city_5': 1005}

population = pd.Series(population_dict)
print(population)
print(population['city_4':'city_5'])

#Для создания Series можно использовать
# - Списки python или массивы numpy
# - скалярное значение
# - словари

city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
dtype: int64
city_4    1004
city_5    1005
dtype: int64


In [5]:
## DataFrame - двумерный массив с явно определенными индексами. Последовательность согласованных по индексам sеries

In [10]:
population_dict= {'city_1': 1001, 'city_2': 1002, 'city_3': 1003, 'city_4': 1004, 'city_5': 1005}
area_dict = {'city_1': 9991, 'city_2': 9992, 'city_3': 9993, 'city_4': 9994, 'city_5': 9995}

population = pd.Series(population_dict)
area = pd.Series(area_dict)

# print(population)
# print(area)

states= pd.DataFrame({'population': population, 'area1':area})
print(states)

print(states.values)
print(states.index)
print(states.columns)

print(type(states.values))
print(type(states.index))
print(type(states.columns))

print(states['area1'])

# DataFrame. Способы создания
# -через объекты Series
# - Списки словарей
# - Словари объектов Series
# - двумерный массив numpy
# - структуризированный массив numpy


        population  area1
city_1        1001   9991
city_2        1002   9992
city_3        1003   9993
city_4        1004   9994
city_5        1005   9995
[[1001 9991]
 [1002 9992]
 [1003 9993]
 [1004 9994]
 [1005 9995]]
Index(['city_1', 'city_2', 'city_3', 'city_4', 'city_5'], dtype='object')
Index(['population', 'area1'], dtype='object')
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.base.Index'>
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64


In [ ]:
# Index - способ организации ссылки на данные объектов Series и DataFrame. Index-неизменяем, упорядочен, является мультимножеством (могут быть повторяющиеся значения)

In [18]:
ind = pd.Index([1,2,3,4,5])
print(ind[1])
print(ind[::2])

# ind[1] = 5 TypeError: Index does not support mutable operations

# Index следует соглашениям объекта set(python)

2
Index([1, 3, 5], dtype='int64')


In [19]:
indA = pd.Index([1,2,3,4,5])
indB = pd.Index([2,3,4,5,6])

print(indA.intersection(indB)) #Пересечение


Index([2, 3, 4, 5], dtype='int64')


In [24]:
# Выборка данных из Series (как словарь)

data = pd.Series([0.25,0.5,0.75,1.0], index=['a', 'b', 'c', 'd'])

print('a' in data)
print('x' in data)

print(data.keys())
print(list(data.items()))

data['a'] =100
print(data)

data['z'] =1000 #Добавили новый элемент
print(data)

True
False
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]
a    100.00
b      0.50
c      0.75
d      1.00
dtype: float64
a    100.00
b      0.50
c      0.75
d      1.00
z    100.00
dtype: float64


In [28]:
## как одномерный массив
data = pd.Series([0.25,0.5,0.75,1.0], index=['a', 'b', 'c', 'd'])

print(data['a':'c'])

print(data[0:2])

print(data[(data>=0.5) & (data<1)])

print(data[['a', 'd']])

a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
b    0.50
c    0.75
dtype: float64
a    0.25
d    1.00
dtype: float64


In [33]:
# атрибуты-индексаторы
data = pd.Series([0.25,0.5,0.75,1.0], index=[1, 3, 10, 15])

print(data[1])
print(data.loc[1])
print(data.iloc[1])

0.25
0.25
0.5


In [42]:
# Выборка данных из DataFrame (как словарь)

population_dict= {'city_1': 1001, 'city_2': 1002, 'city_3': 1003, 'city_4': 1004, 'city_5': 1005}
area_dict = {'city_1': 9991, 'city_2': 9992, 'city_3': 9993, 'city_4': 9994, 'city_5': 9995}

pop = pd.Series({'city_1': 1001, 'city_2': 1002, 'city_3': 1003, 'city_4': 1004, 'city_5': 1005})
area = pd.Series({'city_1': 9991, 'city_2': 9992, 'city_3': 9993, 'city_4': 9994, 'city_5': 9995}
)
data = pd.DataFrame({'area1':area, 'pop1':pop, 'pop': pop})

print(data)
print(data['area1'])
print(data.area1)

print(data.pop1 is data['pop1'])
print(data.pop is data['pop'])

data['new'] = data['area1']/data['pop1'] #add new
print(data)

#двумерный Numpy-массив

        area1  pop1   pop
city_1   9991  1001  1001
city_2   9992  1002  1002
city_3   9993  1003  1003
city_4   9994  1004  1004
city_5   9995  1005  1005
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64
True
False
        area1  pop1   pop       new
city_1   9991  1001  1001  9.981019
city_2   9992  1002  1002  9.972056
city_3   9993  1003  1003  9.963111
city_4   9994  1004  1004  9.954183
city_5   9995  1005  1005  9.945274


In [48]:
data = pd.DataFrame({'area1':area, 'pop1':pop})
print(data)
print(data.values) #2мерный нампи

print(data.T) #transpose

#Доступ к стороке осуществляетсчя через values, дальше массив нампи
print(data['area1'])

print(data.values[0:3])


        area1  pop1
city_1   9991  1001
city_2   9992  1002
city_3   9993  1003
city_4   9994  1004
city_5   9995  1005
[[9991 1001]
 [9992 1002]
 [9993 1003]
 [9994 1004]
 [9995 1005]]
       city_1  city_2  city_3  city_4  city_5
area1    9991    9992    9993    9994    9995
pop1     1001    1002    1003    1004    1005
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64
[[9991 1001]
 [9992 1002]
 [9993 1003]]


In [56]:
#атрибуты-индексаторы

data = pd.DataFrame({'area1':area, 'pop1':pop, 'pop':pop})

print(data)
print(data.iloc[:3, 1:2])
print(data.loc[:'city_4', 'pop1':'pop'])
print(data.loc[data['pop'] >1002, ['area1','pop']])

data.iloc[0,2] = 9999
print(data)

        area1  pop1   pop
city_1   9991  1001  1001
city_2   9992  1002  1002
city_3   9993  1003  1003
city_4   9994  1004  1004
city_5   9995  1005  1005
        pop1
city_1  1001
city_2  1002
city_3  1003
        pop1   pop
city_1  1001  1001
city_2  1002  1002
city_3  1003  1003
city_4  1004  1004
        area1   pop
city_3   9993  1003
city_4   9994  1004
city_5   9995  1005
        area1  pop1   pop
city_1   9991  1001  9999
city_2   9992  1002  1002
city_3   9993  1003  1003
city_4   9994  1004  1004
city_5   9995  1005  1005


In [61]:
rng = np.random.default_rng()
s = pd.Series(rng.integers(0,12,4))

print(s)
print(np.exp(s))

0     4
1     6
2    10
3     6
dtype: int64
0       54.598150
1      403.428793
2    22026.465795
3      403.428793
dtype: float64


In [63]:
pop = pd.Series({'city_1': 1001, 'city_2': 1002, 'city_3': 1003, 'city_41': 1004, 'city_51': 1005})
area = pd.Series({'city_1': 9991, 'city_2': 9992, 'city_3': 9993, 'city_42': 9994, 'city_52': 9995})

data=pd.DataFrame({'area1':area, 'pop1':pop})
print(data)

#NaN - not a number

          area1    pop1
city_1   9991.0  1001.0
city_2   9992.0  1002.0
city_3   9993.0  1003.0
city_41     NaN  1004.0
city_42  9994.0     NaN
city_51     NaN  1005.0
city_52  9995.0     NaN


In [67]:
dfA = pd.DataFrame(rng.integers(0,10,(2,2)), columns=['a', 'b'])
dfB = pd.DataFrame(rng.integers(0,10,(3,3)), columns=['a', 'b', 'c'])

print(dfA)
print(dfB)

print(dfA+dfB)

   a  b
0  2  2
1  0  0
   a  b  c
0  8  3  6
1  6  9  0
2  7  0  2
      a    b   c
0  10.0  5.0 NaN
1   6.0  9.0 NaN
2   NaN  NaN NaN


In [76]:
rng = np.random.default_rng()

A = rng.integers(0, 10,(3,4))
print(A)
# print(A[0])
# print(A - A[0])

df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])
print(df)
print(df.iloc[0])
print(df-df.iloc[0])
print(df.iloc[0, ::2])
print(df-df.iloc[0,::2])

[[9 8 4 1]
 [4 8 3 4]
 [8 2 4 2]]
   a  b  c  d
0  9  8  4  1
1  4  8  3  4
2  8  2  4  2
a    9
b    8
c    4
d    1
Name: 0, dtype: int64
   a  b  c  d
0  0  0  0  0
1 -5  0 -1  3
2 -1 -6  0  1
a    9
c    4
Name: 0, dtype: int64
     a   b    c   d
0  0.0 NaN  0.0 NaN
1 -5.0 NaN -1.0 NaN
2 -1.0 NaN  0.0 NaN


In [82]:
#NaN - not a number
#NA - значения: NaN, null

# Pandas. Два спососба хранения отсутсвующих значний
# ИНдикаторы NaN, None
# null

#None-объект (накладные расходы). Не работает с сум, мин и тд.

vall = np.array([1,2,3])
print(vall.sum())

#TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
# vall = np.array([1,2,3, None])
# print(vall.sum())

vall = np.array([1,2, np.nan,3])
print(vall.sum())
print(np.nansum(vall))

6
nan
6.0


In [86]:
x = pd.Series(range(10), dtype=int)
print(x)

x[0]=None
x[1]=np.nan

print(x) # Число заменили числом

x1 = pd.Series(['a', 'b', 'c'])
print(x1)

x1[0] = None
x1[1] = np.nan

print(x1) # Объект заменили объектом

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64
0    a
1    b
2    c
dtype: object
0    None
1     NaN
2       c
dtype: object


In [96]:
#
x2 = pd.Series([1,2,3, np.nan, None, pd.NA])
print(x2)

x3 = pd.Series([1,2,3, np.nan, None, pd.NA], dtype='Int32')
print(x3)

print(x3.isnull())
print(x3[x3.isnull()])
print(x3[x3.notnull()])

print(x3.dropna())

0       1
1       2
2       3
3     NaN
4    None
5    <NA>
dtype: object
0       1
1       2
2       3
3    <NA>
4    <NA>
5    <NA>
dtype: Int32
0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool
3    <NA>
4    <NA>
5    <NA>
dtype: Int32
0    1
1    2
2    3
dtype: Int32
0    1
1    2
2    3
dtype: Int32


In [102]:
df= pd.DataFrame([[1,2,3, np.nan, None, pd.NA], [1,2,3,None,5,6], [1, np.nan, 3,None, np.nan, 6]])

print(df)
print(df.dropna())
print('                         ')
print(df.dropna(axis=0))
print('                         ')
print(df.dropna(axis=1))

   0    1  2   3    4     5
0  1  2.0  3 NaN  NaN  <NA>
1  1  2.0  3 NaN  5.0     6
2  1  NaN  3 NaN  NaN     6
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5]
Index: []
                         
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5]
Index: []
                         
   0  2
0  1  3
1  1  3
2  1  3


In [106]:
#how

# -all- все значения NA
print(df.dropna(axis=1, how='all'))

# -any- хотя бы одно значение
print(df.dropna(axis=1, how='any'))

# - thresh = x, остается, если присутсвует МИНИМУМ x НЕПУСТЫХ значений
print(df.dropna(axis=1, thresh=2))

   0    1  2    4     5
0  1  2.0  3  NaN  <NA>
1  1  2.0  3  5.0     6
2  1  NaN  3  NaN     6
   0  2
0  1  3
1  1  3
2  1  3
   0    1  2     5
0  1  2.0  3  <NA>
1  1  2.0  3     6
2  1  NaN  3     6
